# source("time_series_JM_SSAR1_logY_norm_norm_1999.R")
# source("time_series_JM_SSAR1_logY_norm_norm_theta_1999.R")
# source("time_series_JM_SSAR1_logY_norm_norm_var_1999.R")
# source("time_series_JM_SSAR1_logY_norm_norm_var_theta_1999.R")
# source("time_series_JM_SSAR1_logY_norm_norm_varM_theta_1999.R")
# source("time_series_JM_SSAR1_logY_norm_norm_varM_thetaM_1999.R")
source("time_series_JM_SSAR1_logY_norm_norm_var_thetaM_1999.R")
source("time_series_JM_SSAR1_logY_norm_norm_thetaM_1999.R")
source("time_series_JM_SSAR1_logY_norm_t_1999.R")
source("time_series_JM_SSAR1_logY_norm_t_theta_1999.R")
source("time_series_JM_SSAR1_logY_norm_t_var_1999.R")
source("time_series_JM_SSAR1_logY_norm_t_var_theta_1999.R")
source("time_series_JM_SSAR1_logY_norm_t_varM_theta_1999.R")
source("time_series_JM_SSAR1_logY_norm_t_varM_thetaM_1999.R")
source("time_series_JM_SSAR1_logY_norm_t_var_thetaM_1999.R")
source("time_series_JM_SSAR1_logY_norm_t_thetaM_1999.R")